### ISSUE TITLE
Section TextColor property does not work

### ISSUE THREAD

**Issue by Tum4ik** [muak/AiForms.SettingsView#100]
### Description
The TextColor propery of Section produces always black text and it is not possible to change color.

### Steps to Reproduce

1. Write a code:
```xaml
<sv:SettingsView>
    <sv:Section Title="{Binding LocalizationService[General]}" TextColor="Red"></sv:Section>
    <sv:Section Title="{Binding LocalizationService[Connection]}" TextColor="Blue"></sv:Section>
</sv:SettingsView>
```
2. Notice that text color of sections is black anyway.

### Expected Behavior
The color of the sections text have to be different.

### Actual Behavior
The color of the sections text is still black.

### Platforms

- [X] Android
- [ ] iOS

### Basic Information

- AiForms.SettingsView 1.0.9
- Xamarin.Forms 4.6.0.800
- Android Support Library Version: 
  - Xamarin.Android.Support.v7.AppCompat 28.0.0.3
  - Xamarin.Android.Support.v7.RecyclerView 28.0.0.3
- Affected Devices: Assistant AP-108 (Android version 8.0.0)

### Screenshots

![Screenshot_20200524-152852](https://user-images.githubusercontent.com/21317790/82754125-97e13300-9dd3-11ea-87e1-a1c17a8e32a1.png)

### Workaround
Adding property `HeaderTextColor` to the `SettingsView` solves the problem.
```xaml
<sv:SettingsView HeaderTextColor="Red">
    <sv:Section Title="{Binding LocalizationService[General]}"></sv:Section>
    <sv:Section Title="{Binding LocalizationService[Connection]}"></sv:Section>
</sv:SettingsView>
```

**Comment by muak** [comment]
@Tum4ik 
Thank you for your report.

Section.TextColor is not supported for now.
Please use HeaderTextColor or FooterTextColor instead of TextColor.

**Comment by Tum4ik** [comment]
yep, as my workaround... Thanks.
