### ISSUE TITLE
Downgrade AI SettingsView netstandard from 2.1 to 2.0

### ISSUE THREAD

**Issue by ChaseFlorell** [muak/AiForms.SettingsView#124]
### Description
We've discovered that the pre-release version depends on netstandard 2.1.
Given that some projects cannot yet move to netstandard 2.1, it would be super if we could revert this dependency in order to make AI SettingsView more accessible 

Or at least multi-target

```xml
<PropertyGroup>
	<TargetFrameworks>netstandard2.1;netstandard2.0;netstandard1.0</TargetFrameworks>
</PropertyGroup>
```

### Steps to Reproduce

1. 
2. 
3. 

### Platforms

- [x] Android
- [x] iOS

### Basic Information

- AiForms.SettingsView x.x.x
- Xamarin.Forms x.x.x
- Android Support Library Version: 
- Affected Devices:

**Comment by jgtaveras** [comment]
Having the same issue here
