### ISSUE TITLE
[Enhancement] AndroidX Support (Multitarget)

### ISSUE THREAD

**Issue by dmariogatto** [muak/AiForms.SettingsView#128]
## Summary
It'd be awesome to have this library setup to used the more modern multitarget approach (similar to Xamarin Essentials). In addition to being the new hotness, it'll also simplify support for Android X.

## API Changes

None, this is a change to the project structure and NuGet packaging.

## Intended Use Case

Native Android X support for apps targeting MonoAndroid10.0!

**Comment by pinewoodranger** [comment]
This would be super. Im playing with the settings controls and they fit my project perfectly but I dont want to release with old 28.0.0.3 app compat libraries.

**Comment by muak** [comment]
@dmariogatto 
Thank you for your suggestion.

I corresponded to AndroidX by the simple method this time.
Thanks.
