### ISSUE TITLE
DatePickerCell not working on iOS 14

### ISSUE THREAD

**Issue by TrueGeek** [muak/AiForms.SettingsView#130]
### Description

On iOS 14 DatePickerCell does not work

### Steps to Reproduce

1. Create a DatePickerCell
2. Use it on an iOS 14 device

### Expected Behavior

When tapped it should popup and display the normal date picker. Which, on 14 is displayed in the middle of the screen as a grid based calendar.

### Actual Behavior

When tapped it displays a date at the bottom. You then have to tap that and then you see the correct control. Then you choose a date and have to click outside the calendar (onto the blurred background). which brings you back to the original image where you have to tap "Done".

### Platforms

- [ ] Android
- [X] iOS

### Basic Information

- AiForms.SettingsView 1.0.9
- Xamarin.Forms 4.8.0.1269
- Affected Devices: All iOS 14 devices

### Screenshots

![image](https://user-images.githubusercontent.com/90821/94014569-bb17f100-fd79-11ea-9417-06e418633e75.png)

![image](https://user-images.githubusercontent.com/90821/94014624-cbc86700-fd79-11ea-996f-80c47ce398d1.png)

### Workaround

The only workaround is to hope users will tap on the date and figure it out.

**Comment by TrueGeek** [comment]
This looks like it may be a Xamarin issue. [Bug 11963](https://github.com/xamarin/Xamarin.Forms/issues/11963).

Currently still open but it looks like they [just merged a PR](https://github.com/xamarin/Xamarin.Forms/commit/fe09556720d1241cabf68cf1b4ab5a2d42de50ad) with a possible fix yesterday.

We haven't had a customer complain about this yet so with any luck Xamarin will publish their update before anyone notices. 😀 When they do I'll test and update back here if this also fixes AiForms.

**Comment by muak** [comment]
@TrueGeek 
Thank you for the helpful information.

I corresponded to iOS14 by set ``UIDatePickerStyle.Wheels``.
