### ISSUE TITLE
[Enhancement] Map AutomationIDs

### ISSUE THREAD

**Issue by wilda17** [muak/AiForms.SettingsView#140]
In order to auto test apps via e.g. Appium it is neccessary to have AutomationIDs set in Xamarin.Forms Elements. This maps to ContentDescription of Views in Android and to AccessibilityIdentifier on iOS.

Since a SettingCell more or less corresponds to one item/element in terms, automation/accessibility it seems appropriate of mapping the AutomationID to the containers (contentview, contentstack) on the respective platforms.

**Comment by muak** [comment]
@wilda17 
Thank you for your report.

This issue fixed by https://github.com/muak/AiForms.SettingsView/pull/143.
