### ISSUE TITLE
Picker Header and Footer Color

### ISSUE THREAD

**Issue by LaBoss** [muak/AiForms.SettingsView#142]
### Description
Hello how to change color of header ans footer on picker?

![Sem Título](https://user-images.githubusercontent.com/5363187/106883761-5467f400-66d8-11eb-961b-e3f5497c7141.png)

### Steps to Reproduce
My Color Settings

`<Style TargetType="sv:SettingsView">
                <Setter Property="SeparatorColor" Value="{StaticResource Accent}" />
            
                <Setter Property="HeaderBackgroundColor" Value="Red" />
                <Setter Property="CellBackgroundColor" Value="{StaticResource AppBackground}" />
                <Setter Property="BackgroundColor" Value="{StaticResource AppBackground}" />
                <Setter Property="SelectedColor" Value="{StaticResource LightText}" />
                

                <Setter Property="CellTitleColor" Value="{StaticResource LightText}" />
                <Setter Property="CellValueTextColor" Value="{StaticResource Accent}" />
                <Setter Property="CellDescriptionColor" Value="{StaticResource LightGrey}" />
                <Setter Property="CellAccentColor" Value="{StaticResource Accent}" />
                <Setter Property="HeaderTextColor" Value="{StaticResource LightText}" />
                <Setter Property="FooterTextColor" Value="{StaticResource LightText}" />

                
                <Setter Property="HeaderFontSize" Value="{StaticResource BaseFontSize+}" />
                <Setter Property="FooterFontSize" Value="{StaticResource BaseFontSize+}" />
                <Setter Property="CellTitleFontSize" Value="{StaticResource BaseFontSize+}" />
                <Setter Property="CellDescriptionFontSize" Value="{StaticResource BaseFontSize-}" />
                <Setter Property="CellValueTextFontSize" Value="{StaticResource BaseFontSize+}" />
            </Style>`

**Comment by muak** [comment]
@LaBoss 

For Android,  dialog color can be changed by using a style like the following.

```xml
   <!-- Base theme applied no matter what API -->
    <style name="MainTheme.Base" parent="Theme.AppCompat.DayNight">
        <item name="android:datePickerDialogTheme">@style/AppCompatDialogStyle</item>
	<item name="android:alertDialogTheme">@style/AppCompatDialogStyle</item>
	<item name="android:timePickerDialogTheme">@style/AppCompatDialogStyle</item>
    </style>
    <style name="AppCompatDialogStyle" parent="Theme.AppCompat.DayNight.Dialog">
        <item name="colorAccent">@color/colorAccent</item>
		<item name="android:textColorPrimary">@color/normal_text</item>		
		<!-- android:background desn't work. Use the following instead of -->
		<item name="android:windowBackground">@color/dialog_back</item>
		<!-- When use full custom TimePicker -->
		<!-- <item name="android:timePickerStyle">@style/TimePickerDialogStyle</item> -->
    </style>
```
