### ISSUE TITLE
Picker Selected Items not Ticked on iOS running Xamarin Shell

### ISSUE THREAD

**Issue by OnTheFenceDevelopment** [muak/AiForms.SettingsView#151]
### Description
When running a Xamarin.Forms application, using Shell navigation, under iOS the selected items are not displayed when expanding to reveal the Items List.

### Steps to Reproduce

1. Create a Xamarin.Forms Shell application
2. Add and implement SettingsView as per ReadMe
3. Add PickerCell and populate ItemSource as per ReadMe
4. Run application on iOS (Device or Simulator)
5. Tap Picker to expand and display configured items
6. Select multiple items
7. Tap Back to return to Settings Page
8. Tap Picker to expand and display configured items

### Expected Behavior
The items selected in step 6 to be selected

### Actual Behavior
No items are selected

### Platforms

- [ ] Android
- [ X] iOS

### Basic Information

- AiForms.SettingsView 1.3.12
- Xamarin.Forms 5.0.0.2021
- Android Support Library Version: 
- Affected Devices:

### Screenshots
TBA

### Workaround
The sample application works as expected as it does not currently use the Xamarin Shell. I have located the source of the issue and will submit a Pull Request shortly

**Comment by muak** [comment]
@OnTheFenceDevelopment 
Your pr was merged.
Thanks!😄
