### ISSUE TITLE
Refering Xamarin.AndroidX.Core package version 1.3.2.2 or higher makes System.TypeLoadException error.

### ISSUE THREAD

**Issue by ivoryguard** [muak/AiForms.SettingsView#157]
### Description

Refering Xamarin.AndroidX.Core package version 1.3.2.2 or higher makes System.TypeLoadException error as the following;

System.TypeLoadException
  Message=VTable setup of type AiForms.Renderers.Droid.SettingsViewLayoutManager failed

### Steps to Reproduce

1. Create a Xamarin.Forms project and refer AiForms.SettingsView package
2. Add a SettingsView into a ContentPage
3. Add any package which has dependency of Xamarin.AndroidX.Core package version 1.3.2.2 or higher like Xamarin.AndroidX.Media
4. When SettingsView control is created, System.TypeLoadException error occurs.

### Platforms

- [x ] Android
- [ ] iOS

### Workaround

Downgrade the Xamarin.AndroidX.Core package to version to 1.3.2.1.

Please, refer Telerik's posting - https://docs.telerik.com/devtools/xamarin/knowledge-base/common-typeloadexception-accessibilitydelegatecompat

**Comment by ScarletKuro** [comment]
Got the same problem

**Comment by muak** [comment]
@ivoryguard 
Thank you for your report.

I face the same issue too.

But Xamarin.Forms 5.0.0.2012 is still used Xamarin.AndroidX.Core 1.3.2.1(as a dependency of Xamarin.Google.Android.Material 1.2.1.1).
So we have no choice but to downgrade to AndroidX.Core 1.3.2.1 for now.
(refer 
https://www.telerik.com/forums/system-typeloadexception-when-using-listview#5297172)

Please wait for Xamarin.Forms update.

**Comment by muak** [comment]
This issue is solved by Xamarin.Forms 5.0.0.2083.
If you installed AndroidX.Core.1.3.21, you need to uninstall it.
