### ISSUE TITLE
missing Customizeable font

### ISSUE THREAD

**Issue by ghatighorias** [muak/AiForms.SettingsView#30]
I could not find the way to set custom font. or to set up font attribute like bold or italic.
is there a way to set them up ?

**Comment by muak** [comment]
At the moment, there isn't the way of what you want to do.
But I accepted them as requests.

Thank you.

**Comment by ali-h2010** [comment]
Hi @muak ,
What are the updates on this customization request?
Can we edit the font in the source code and create a custom nuget package as a work around for the time being?

**Comment by ali-h2010** [comment]
I was able to set the font in the sample in **CellBaseView**

` public CellBaseView(Cell formsCell) : base(UIKit.UITableViewCellStyle.Default, formsCell.GetType().FullName)
        {
            Cell = formsCell;

            SelectionStyle = UITableViewCellSelectionStyle.None;
            SetUpHintLabel();
            SetUpContentView();

            UpdateSelectedColor();

            TitleLabel.Font = UIFont.FromName("Times New Roman", 20f);
            HintLabel.Font = UIFont.FromName("Times New Roman", 20f);
            DescriptionLabel.Font = UIFont.FromName("Times New Roman", 20f);
        }`

But how can i apply this in my project?
Should i try to edit the font in the source and create a nuget package?
Can i overrise the cellbaseview in my project and edit what i want if they are public?

**Comment by ali-h2010** [comment]
I am not able to override the properties of the cell since it has a private set
public UILabel HintLabel { get; private set; }

**Comment by ShahmanTeh** [comment]
can you try reflection in this case ? (as a workaround)

**Comment by ali-h2010** [comment]
@ShahmanTeh Thanks for your suggestion.
Did anyone try to create a Nuget of the solution?
when creating one and adding it to a different project, i am getting multiple error forms like:
multiple assemblies with equivalent identity have been imported ...

**Comment by muak** [comment]
@ShahmanTeh 
Thank you for replying.

@ali-h2010 
Since the subclass of the BaseCellView can't be inserted in any cell renderers, you should create the subclass of each cell renderer and the subclass of the CellBaseRenderer.
For example:

```cs
public class ExCellBaseRenderer<TnativeCell> : CellBaseRenderer<TnativeCell>
{
    public override UITableViewCell GetCell(Cell item, UITableViewCell reusableCell, UITableView tv)
    {
        var nativeCell = base.GetCell(item, reusableCell, tv);

        nativeCell.TitleLabel.Font = UIFont.FromName("Times New Roman", 20f);
        nativeCell.HintLabel.Font = UIFont.FromName("Times New Roman", 20f);
        nativeCell.DescriptionLabel.Font = UIFont.FromName("Times New Roman", 20f);

        return nativeCell;
    }
}
```

```cs
assembly: ExportRenderer(typeof(LabelCell), typeof(ExLabelCellRenderer))]
namespace AiForms.Renderers.iOS
{
    public class ExLabelCellRenderer : ExCellBaseRenderer<LabelCellView> { }   
}
```

Since this code is written with my imagination, I don't know whether it works or not actually.

**Comment by muak** [comment]
@ghatighorias @ali-h2010 
Thank you for waiting.

This feature was implemented.
