### ISSUE TITLE
Android 5.0 support

### ISSUE THREAD

**Issue by pfedotovsky** [muak/AiForms.SettingsView#31]
Readme states that minimal version is "Android:version 5.1.1 (only FormsAppcompatActivity) / API22". 
I'd love to use this project in my app, but I need Android 5.0 support. Is there reason why it's not supported? Or probably just not all the features are available?

**Comment by muak** [comment]
@pfedotovsky 

Thank you for considering this library.

The only reason is that the real device that I own is API22.
So this library might work in reality on API21 but it isn't supported.

I'm sorry for not replying your expectation.
