### ISSUE TITLE
Setting SelectedItems for PickerCell

### ISSUE THREAD

**Issue by liamself** [muak/AiForms.SettingsView#33]
I'm looking to save the selected items from a PickerCell to restore them when the app is closed and re-opened. I can do this for SwitchCells, however when using a PickerCell, when some items are selected and the back button pressed, the set method for the bound object (An ObservableCollection) does not fire, and while I can get around this by using the SelectedCommand to update the setting, when the app reloads, SelectedItems does not select the items specified in the List it is bound to.

What is the intended method to set the selected items in a PickerCell?

**Comment by muak** [comment]
@liamself 
Hi, please use SelectedItems property like following code.

```cs
public ObservableCollection<Person> ItemsSource { get; }
public ObservableCollection<Person> SelectedItems { get;set; }

public SomeViewModel()
{
    ItemsSource = new ObservableCollection<Person>(sourcelist);
    Restore();
}
void Restore()
{
    SelectedItems = new ObservableCollection<Person>(
        ItemsSource.Where(x => x.Age > 20) // Add items from ItemsSource elements.
   );
}
```

```xml
<ai:Section Title="Section1" >
    <ai:PickerCell  ItemsSource="{Binding ItemsSource}" SelectedItems="{Binding SelectedItems}"  />
</ai:Section>
```

Note that SelectedItems property must be set each ItemsSource element instance.

Thank you.

**Comment by muak** [comment]
This issue might be solved by the recent update.
