### ISSUE TITLE
EntryCell IsPassword Property

### ISSUE THREAD

**Issue by matteopiccioni** [muak/AiForms.SettingsView#37]
Hello,
is possibile to have IsPassword property for EntryCell cell type?
I think could be useful.

Otherwise to get the same result you are forced to use a custom cell
Thanks

**Comment by muak** [comment]
@matteopiccioni 
Hi,

I'm sorry that it is impossible to use password mode for now.
I accept this as a request.

I also consider that I will implement the structure you can freely add a custom cell.
Thank you 😀
