### ISSUE TITLE
SwitchCell event?

### ISSUE THREAD

**Issue by nbsoftware** [muak/AiForms.SettingsView#45]
Hello,

I started to use your great component as it undoubtedly adds great flexibility when designing a settings form.

Everything is fine so far except the SwitchCell. (and most likely the CheckCell also).

Probably a newbie question, but apart from the cell Tapped event , I don't see any event attached to the switch itself i.e. if the user touches the switch and changed its value, I cannot see any mean to immediately trigger some code and react to the change - which I need because in my use case, changing the switch must subscribe / unsubscribe the user to some push notifications.

Any clue?
Thanks

**Comment by nbsoftware** [comment]
Brillant!

Thanks @muak for answering so quickly and with a solution that worked flawlessly.

When you work on Switch / Check changed command - and I think it will indeed be helpful to simplify user code - please don't forget the old non MVVM model where plain old events are still needed ;)

As a matter of fact, your sample code in the `README.md` does list for instance `LoadApplication(new App(new iOSInitializer()));` where `iOSInitializer()` is from Prism if I am correct, which not everyone uses ;)

Again, thank you very much!

**Comment by nbsoftware** [comment]
Hi again.

I spoke a tad too quickly ;)

While in iOS everything is working as expected, in Android and with your method, SwitchCells respond either to clicking on the switch but also tapping on the cell elsewhere even if no Tapped event has been registered.

And in this case, it enters in the subscribed PropertyChanged event with the "On property".

Again, it does not in iOS.

Any clue?

Thanks

**Comment by nbsoftware** [comment]
Hi @muak,

Have you been able to look into this?

To describe it further, on Android it does not distinguish between a Tapped event or just a click on the switch. If I register both a Tapped event and the PropertyChanged event, when clicked on the switch it fires the PropertyChanged event only, i.e. as expected, but if I tap in the cell, it fires first the Tap event and then the PropertyChanged event with a change to the switch value which is wrong because I didn't click on the switch nor did I want to change its value.

On iOS, with the same scenario, when tapped in the cell it only fires the Tap event as I would have expected.

Thanks

**Comment by muak** [comment]
@nbsoftware 

The behavior that it responds only a switch on iOS and it responds entire SwitchCell on Android is my intended behavior.
Because I incorporated the general setting page behavior of each platform (such as Google apps on Android, system settings on iOS).
I believe each platform user is easy to accept the behavior.

I'm sorry for not replying your expectation.

Thank you.

**Comment by nbsoftware** [comment]
Thanks @muak for your answer.

No problem, I'm just trying to figure this out ;)

I definitively understand your concern as to respecting each platform's native behavior.

So ok, you are right, on the Android platform, tapping in cells of a standard settings view does the same thing as tapping on the switch for regular apps such as Google Apps.

And on iOS, tapping in the cell does nothing as far as the switch is concerned.

But then, if I may, it won't be entirely consistent until a switch event is implemented for iOS as you suggested it earlier which was the beginning of this post.

Ok then, I'll try do to without for the time being.

Thanks for you answers and for your great component nonetheless ;)

**Comment by muak** [comment]
@nbsoftware 

Thank you for your understanding😄
