### ISSUE TITLE
[Enquiry] Section ItemTemplate

### ISSUE THREAD

**Issue by ShahmanTeh** [muak/AiForms.SettingsView#47]
Hi, i checked that there is a ItemTemplate for section.

was this meant for customizing section?

**Comment by muak** [comment]
@ShahmanTeh 

Hi,
A Section ItemTemplate is what each cell is repeatedly arranged with a DataTemplate as the following code:

```xml
<sv:Section ItemsSource="{Binding ItemsSource}">
    <sv:Section.ItemTemplate>
        <DataTemplate>
            <sv:LabelCell Title="{Binding Name}" Value="{Binding Address}" />
        </DataTemplate>
    </sv:Section.ItemTemplate>
</sv:Section>
```

About more information for DataTemplate, would you please see [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/creating).
