### ISSUE TITLE
Custom Cell does not have selection/ripple selection

### ISSUE THREAD

**Issue by ShahmanTeh** [muak/AiForms.SettingsView#50]
Hi I used a ViewCell in the SettingsView and did not be able to show highlighting.

**Comment by muak** [comment]
@ShahmanTeh 

The selection effect is only contained in the cell derived from CellBaseView of SettingsView.
As a ViewCell is not so, consider AddCommand or Feedback of [AiForms.Effects](https://github.com/muak/AiForms.Effects) instead of.

**Comment by muak** [comment]
@ShahmanTeh 
You can use the CustomCell.
Thanks.
