### ISSUE TITLE
iOS crashes and android works...

### ISSUE THREAD

**Issue by jmah322** [muak/AiForms.SettingsView#51]
I am new to AiForms.SettingsView.  However, I have followed the instructions in details and added the required code in AppDelegate.cs -- AiForms.Renderers.iOS.SettingsViewInit.Init(); in FinishedLaunching.  However, when I installed the app in iOS (iPhone6 and iOS version=11.4.1), it crashes and the app disappers.  The Android app works as expected.  What am I doing wrong?  I have googled everywhere looking for clues and can't seem to find any.  

Let me know

**Comment by muak** [comment]
@jmah322 

Thank you for your report.

I'm not able to reproduce it.
It correctly worked on my iOS Simulator v.11.4.

Would you please tell me more detail?

**Comment by jmah322** [comment]
Hi Kamu,

Thank you for getting back to me so quickly.  I am building to an actual device through AppCenter.  Below is the build configuration:



My Android build works great.  However, when I created a simple xaml page with AiForms, the iOS app crashes.  I have been googling looking for others with similar problem.  I can’t find anything on it.  So, I think it’s mine issue.  I just don’t know where to look or isolate the issue further.  

Thanks for the quick response!

Sent from Mail for Windows 10

**Comment by jmah322** [comment]
Hi Kamu,

I am not sure what happened.  But, AiForms.ViewSettings is working for me now on iOS.  

Sent from Mail for Windows 10

**Comment by jmah322** [comment]
It works on iOS for me now.
