### ISSUE TITLE
AndroidEnablePreloadAssemblies - Empty SettingsView

### ISSUE THREAD

**Issue by matteopiccioni** [muak/AiForms.SettingsView#60]
Hello,
in Xamarin.Android 9.2 release notes, Microsoft suggest to disable AndroidEnablePreloadAssemblies to have shorten startup times 

In my case, if I edit my Android project adding 
```
<PropertyGroup>
    <AndroidEnablePreloadAssemblies>false</AndroidEnablePreloadAssemblies>
</PropertyGroup>
```
as described [here](https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.2),
my SettingsView page is empty.
Thanks

**Comment by muak** [comment]
@matteopiccioni 
Thank you for your report.

I have tried that setting and executed debug build and release build.
That correctly worked and a SettingsView was displayed.

This issue may be something to depend on your environment.

My environment is:
VS for Mac 8.0.6 build 4
Target Framework Android 9.0
SettingsView 0.4.15
Xamarin.Forms 4.0.0.425677

**Comment by muak** [comment]
Please try this work around for now.
```
        public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
	{
		protected override void OnCreate(Bundle bundle)
		{
			...
			global::Xamarin.Forms.Forms.Init(this, bundle);
                        new AiForms.Renderers.Droid.LabelCellRenderer(); // instantiate some SettingsView class

		}
	}
```

I will define an initialize method on SettingsView for Android in the next version.

**Comment by matteopiccioni** [comment]
Yes, your work around solve the problem
Thanks

**Comment by muak** [comment]
@matteopiccioni 
I released a new version.
Please try it.

**Comment by matteopiccioni** [comment]
Yes, it works
Thank you!
