### ISSUE TITLE
SetFocus on EntryCell (Request)

### ISSUE THREAD

**Issue by let92** [muak/AiForms.SettingsView#63]
Is there a possibility that you can add the method SetFocus for the EntryCell?
It would be perfect for a login page (that I use with this library).

**Comment by muak** [comment]
@let92 
Thank you for your request.
For now, a method like a SetFocus is not implemented.
I consider it.

Thanks.

**Comment by let92** [comment]
Nice, thank you.

**Comment by muak** [comment]
@let92 
This feature was implemented in ver.1.1.1-pre.
