### ISSUE TITLE
Android 5.0 and iPhone5 support

### ISSUE THREAD

**Issue by ivoryguard** [muak/AiForms.SettingsView#66]
Hello.

AiForms.SettingsView is beatiful and what I want exaclty.

Howerver, I have to make my app support Android 5.0 and iPhone5 with iOS 10.

According to readme, Minumum platform is Android 5.1 and iPhone5s with iOS 9.3

Is there any reason like missing API on implementing?
Do you have a plan to support Anodroid 5.0 and iPhone 5 with iOS 10?

Best regards.

**Comment by ivoryguard** [comment]
I read previous issues and you wrote it supported Android APl level 22 because you have a device of Android 5.1 only.

Does it means that there is no techinical restriction for Android 5.0 and iPhone 5?

Best regards.

**Comment by ivoryguard** [comment]
I tested some cells of SettingsView on my Android 5.0.1 phone and they works well.
SettingsView must work with Android 5.0.1 technincally, if you do not use Android API Level 22 or higher.

**Comment by muak** [comment]
@ivoryguard 
Thank you for trying this library.

I don't have that plan. 
Because I have no way of making sure it whether there is a technical restriction.

I appreciate your testing.
