### ISSUE TITLE
TextPickerCell allows to edit the option in the dropdown on Android

### ISSUE THREAD

**Issue by pantelisGeo90** [muak/AiForms.SettingsView#68]
Hello,
Great package 👍 
On Android:
In my settings page and i am using a `sv:TextPickerCell` and noticed that when the dropdown is visible (user taps in order to select an option from the popup selector) i can see the cursor blinking at the end of the word. if i tap on the selected option then the keayboard comes up and the option gets blank. It does not override the option but the fact that it bring the keyboard up and showing the cursor is something that was not anticipated. See image attached.
Is there an option on the TextPickerCell in order to avoid this behaviour? Something like 'do not allow the user to type on the text cell'?

![1](https://user-images.githubusercontent.com/6824561/64964328-c301a300-d892-11e9-8205-73c6fbba11c4.jpg)

Thank you.

**Comment by muak** [comment]
@pantelisGeo90 

Thank you for your report.
This issue was a simple mistake.
I will fix it not to show the soft keyboard.

Please wait for a while until the next release.

**Comment by pantelisGeo90** [comment]
Hi @muak ,
Thank you very much for looking into that. 👍 🎉
