### ISSUE TITLE
All cells crashes with null reference exception when used as Embedded Forms Fragments

### ISSUE THREAD

**Issue by follesoe** [muak/AiForms.SettingsView#69]
When embedding Xamarin.Form pages into a Xamarin.Android native app the app crashes with a Null Reference Exception. The reason for this exception is this code line: 

https://github.com/muak/AiForms.SettingsView/blob/master/SettingsView.Droid/Cells/CellBaseView.cs#L102

` var contentView = (_Context as FormsAppCompatActivity).LayoutInflater.Inflate(Resource.Layout.CellBaseView, this, true);`

When used in an embedded context, you cannot assume `_Context` is of type `FormsAppCompatActivity`.

Information about embedding: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-forms

**Comment by muak** [comment]
@follesoe 
Thank you for your report.

This issue is fixed in :
https://github.com/muak/AiForms.SettingsView/pull/79
