### ISSUE TITLE
Is there a way to have a custom cell instead of using a cell that derives from basecell?

### ISSUE THREAD

**Issue by pantelisGeo90** [muak/AiForms.SettingsView#70]
Hello, i was wondering if there is an option to use a "custom cell", something like `ViewCell` on xamarin's out-of-the-box [`TableView`](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/tableview#custom-cells).

I tried to do this but i don't think i am in the right track:
![image](https://user-images.githubusercontent.com/6824561/65412286-d5299700-dde6-11e9-8e7a-9df0cc314c2a.png)

Thank you in advance.

**Comment by muak** [comment]
@pantelisGeo90 
The CustomCell comes at the next release.
Please wait for a while.

Thank you.

**Comment by pantelisGeo90** [comment]
wow, awesome @muak 
Thank you for your reply :)
How would we know that this is merged in to master? Should we keep an eye out on your PRs?

**Comment by muak** [comment]
@pantelisGeo90 

Thank you for waiting.
CustomCell was implemented in ver.1.1.1-pre.
