### ISSUE TITLE
TextPicker 'loops through' the items on Android

### ISSUE THREAD

**Issue by pantelisGeo90** [muak/AiForms.SettingsView#72]
Hello again, :)

I've noticed that the `TextPickerCell` does a circular display of the items list. Tested on Android. Haven't tested on iOS.
It loops through the items and the user doesn't know which is the first option and which is the last option. 
Is there a way to disable this behaviour? Maybe an option i missed on the `TextPickerCell` element?

For example as the user scrolls and reaches the end of the options list (inside the dropdown) you can see the initial options as you scroll.

**Comment by muak** [comment]
@pantelisGeo90 

Thank you for your report.

I regret to say that I could'nt confirm this issue on Android.

**Comment by muak** [comment]
@pantelisGeo90 
Thank you for waiting. 

IsCircularPicker Property will enable you to control circulating items in the next release.
Thanks.

**Comment by pantelisGeo90** [comment]
Hi muak,
Thank you very much for getting back regarding this issue. 👍
