### ISSUE TITLE
[Android] SettingsViewRenderer -> NullReferenceException When Navigating Quickly (Shell)

### ISSUE THREAD

**Issue by dmariogatto** [muak/AiForms.SettingsView#73]
When navigating quickly between pages (testing using tabs in Shell) it is possible to get a `NullReferenceException` from the `SettingsViewRenderer` in Android.

`System.NullReferenceException: Object reference not set to an instance of an object.
   at AiForms.Renderers.Droid.SettingsViewRenderer.<ParentPageAppearing>b__7_0 () [0x00000] in <cdcfacab2e6d46f39f91bfaaf30ac508>:0`

Debugging locally this occurs when `Dispose` is called right after the `ParentPageAppearing` event is fired, and before `_adapter.DeselectRow()` can run on the UI thread. Since the object has been disposed `_adapter` is null.

Maybe modify the call to handle the disposed case,
`Device.BeginInvokeOnMainThread(() => _adapter?.DeselectRow());`

**Comment by muak** [comment]
@dmariogatto 
Thank you for your report.

I will apply your code `Device.BeginInvokeOnMainThread(() => _adapter?.DeselectRow());`
in the next release.

Thanks.
