### ISSUE TITLE
[iOS] Is there option to hide the ">" on the right side of the Command Cell 

### ISSUE THREAD

**Issue by AlvinKwong** [muak/AiForms.SettingsView#74]
Only on the iOS version, the `CommandCell` has a light color ">" appearing right next to the `ValueText`. This ">" does not appear on the Android version. 

Is it possible to hide/remove this symbol? 
As it does not look good right next to the `ValueText`.

**Comment by muak** [comment]
@AlvinKwong 

For now, It is not possible to hide/remove The CommandCell indicator.
You can use the ButtonCell instead of.

**Comment by muak** [comment]
@AlvinKwong 
You can use the HideArrowIndicator property on the next release.
Thanks.
