### ISSUE TITLE
Populate SettingsView from code behind

### ISSUE THREAD

**Issue by OKameric** [muak/AiForms.SettingsView#75]
Hi,

awesome library!

Is it possible to populate SettingsView and Section item template and item source from code behind? Do you have an example somewhere? 

Thanks,
Osman

**Comment by muak** [comment]
@OKameric 

Will you please see the following link:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/creating#creating-an-inline-datatemplate
