### ISSUE TITLE
TextPickerCell might access wrong/invalid index on iOS when re-used

### ISSUE THREAD

**Issue by cpraehaus** [muak/AiForms.SettingsView#76]
Hello muak (sorry I don't know your real name), 

First thanks for **great project**, I really like it!
During testing on iOS (11 and 12) I discovered a problem which caused the app to abort.

To explain: my settings view has 3 text picker cells. When scrolling down to the third one the first renderer is "out of view" and probably gets recycled/reviewed by the OS/UI toolkit. That's the point where the app aborts.

As I understand it, the renderer (UIPickerView) of the first TextPickerCell is re-used (recycled) and loaded with the model/data of the third TextPickerCell (which is becoming visible). When updating items of the re-used TextPickerCellRenderer the underlying iOS UIPickerView might access the view model based on stale view data. This can cause index out of range errors and other inconsistencies when the underlying model data was already updated.

In my case the first list (backing the first text picker) and the selected index were larger than the third list (backing the third text picker). Therefore I'm getting the following exception when scrolling in the settings view:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index occurred
```
With the following backtrace
```
0xC in System.ThrowHelper.ThrowArgumentOutOfRange_IndexException at /Library/Frameworks/Xamarin.iOS.framework/Versions/12.4.0.64/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/throwhelper.cs:158,13	C#
0x1B in System.Collections.Generic.List<angel_core.Logging.LogLevel>.get_Item at /Library/Frameworks/Xamarin.iOS.framework/Versions/12.4.0.64/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:182,17	C#
0x2 in System.Collections.Generic.List<angel_core.Logging.LogLevel>.System.Collections.IList.get_Item at /Library/Frameworks/Xamarin.iOS.framework/Versions/12.4.0.64/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:207,17	C#
0xC in AiForms.Renderers.iOS.TextPickerSource.GetTitle	C#
0xFFFFFFFFFFFFFFFF in ObjCRuntime.Messaging.void_objc_msgSend_nint_nint_bool	C#
0x1B in UIKit.UIPickerView.Select at /Library/Frameworks/Xamarin.iOS.framework/Versions/12.4.0.64/src/Xamarin.iOS/UIKit/UIPickerView.g.cs:212,5	C#
0x53 in AiForms.Renderers.iOS.TextPickerCellView.Select	C#
0x2D in AiForms.Renderers.iOS.TextPickerCellView.UpdateItems	C#
0x7 in AiForms.Renderers.iOS.TextPickerCellView.UpdateCell	C#
0xFFFFFFFFFFFFFFFF in AiForms.Renderers.iOS.CellBaseRenderer<AiForms.Renderers.iOS.TextPickerCellView>.GetCell	C#
0x4B in AiForms.Renderers.iOS.SettingsTableSource.GetCell	C#
0xFFFFFFFFFFFFFFFF in UIKit.UIApplication.UIApplicationMain	C#
0xB in UIKit.UIApplication.Main at /Library/Frameworks/Xamarin.iOS.framework/Versions/12.4.0.64/src/Xamarin.iOS/UIKit/UIApplication.cs:79,4	C#
0x2F in UIKit.UIApplication.Main at /Library/Frameworks/Xamarin.iOS.framework/Versions/12.4.0.64/src/Xamarin.iOS/UIKit/UIApplication.cs:63,4	C#
>	0x8 in angel_app.iOS.Application.Main at C:\Users\ChrPra00\Documents\Work\Angel\angel_app\angel_app\angel_app.iOS\Main.cs:17,4	C#
```

I added a fix which resolved the problem for me and will post a PR so you can review it.

Cheers,
Christian.

**Comment by muak** [comment]
@cpraehaus 

Thank you for your report and PR.
I merged it.

This fix version will be reflected for the next release.
Thanks😄
