### ISSUE TITLE
CustomCell does not support auto-sizing

### ISSUE THREAD

**Issue by paya-cz** [muak/AiForms.SettingsView#82]
I use a CustomCell with an `AutoSize` `Editor`. The cell always stays the same height and does not resize (on iOS, haven't tried Android). Instead, the editor overflows the cell after I put in some text.

If I use the stock `TableView`, I can use a `ViewCell` and attach an effect to the `TableView` such that whenever the `Editor` text changes, the following code is called on the `UITableView`:

```c#
DispatchQueue.MainQueue.DispatchAsync(() =>
{
    tableView.BeginUpdates();
    tableView.EndUpdates();
});
```

This resizes the cell and even does a nice animation.

However, this approach seems to not work with `CustomCell` and `SettingsView`. The above code snippet seems to resize the cell back to the one-line size, and the editor just overflows:

<img width="342" alt="Screenshot 2020-02-19 at 19 00 55" src="https://user-images.githubusercontent.com/10402560/74832576-83daf080-530f-11ea-91a3-ce58205e535c.png">

Notice that the header is also clipped when used in a page within AppShell.

### Basic Information

- AiForms.SettingsView 1.1.1-pre
- Xamarin.Forms 4.4.0
- Affected Devices: iOS

**Comment by muak** [comment]
@paya-cz 
Thank you for your report.

I consider implementing a method like ForceUpdate() for the CustomCell.

**Comment by muak** [comment]
@paya-cz 

Cell.Reload method was implemented in ver.1.3.4.
Please try it.

**Comment by aherrick** [comment]
@muak hi! can you provide a quick example which shows how to use the Cell Reload functionality with Entry?

```
  <sv:SettingsView HasUnevenRows="True">
        <sv:Section>
            <sv:EntryCell Title="Name" Placeholder="Name (Optional)" TextAlignment="End" />
            <sv:EntryCell Title="Email" Placeholder="Email (Optional)" TextAlignment="End" Keyboard="Email" />
            <sv:CustomCell x:Name="customCell">
                <Editor Placeholder="Your Feedback is valued! Please add a note here." TextChanged="Editor_TextChanged" Completed="Editor_Completed" AutoSize="TextChanges" MaxLength="4000" />
            </sv:CustomCell>
        </sv:Section>
    </sv:SettingsView>
```

```
        private void Editor_TextChanged(object sender, TextChangedEventArgs e)
        {
            customCell.Reload();
        }

        private void Editor_Completed(object sender, System.EventArgs e)
        {
            customCell.Reload();
        }
```

Doesn't work. Thank you!
