### ISSUE TITLE
Section header/footer does not respect SafeAreaInsets

### ISSUE THREAD

**Issue by paya-cz** [muak/AiForms.SettingsView#83]
### Description

When I put the `SettingsView` in landscape, the header and footer is not considering `SafeAreaInsets`, thus the notch can make part of the header/footer unreadable.

### Platforms

- [x] iOS

### Basic Information

- AiForms.SettingsView 1.1.1-pre
- Xamarin.Forms 4.4.0

I use AppShell

### Screenshots

<img width="744" alt="Screenshot 2020-02-19 at 19 15 04" src="https://user-images.githubusercontent.com/10402560/74833518-88080d80-5311-11ea-85f8-70da666868a8.png">

**Comment by muak** [comment]
@paya-cz 
Thank you for your report.

I fixed it.
Please wait for some while until the next version is released.
