### ISSUE TITLE
SettingsView clipped when used in Shell's ContentPage

### ISSUE THREAD

**Issue by paya-cz** [muak/AiForms.SettingsView#87]
### Description

SettingsView's Section header is partially clipped by Shell NavBar.

### Steps to Reproduce

1. Create a new Xamarin.Forms Shell application
2. Create a new ContentPage
3. Put SettingsView into the ContentPage.Content
4. Add a Section with a Header and Footer

### Expected Behavior

The header of the section should not be clipped.

### Actual Behavior

The header of the section is clipped.

### Platforms

- [ ] Android
- [x] iOS

### Basic Information

- AiForms.SettingsView 1.1.4-pre
- Xamarin.Forms 4.5.0

### Screenshots

<img width="345" alt="Screenshot 2020-03-20 at 19 31 20" src="https://user-images.githubusercontent.com/10402560/77164146-8b74ed00-6aa7-11ea-9b73-e5f7ace97fcc.png">

**Comment by muak** [comment]
@paya-cz 
Thank you for your report.

This issue was fixed at version 1.1.9-pre.
