### ISSUE TITLE
Section footer does not resize when the content wraps to multiple lines.

### ISSUE THREAD

**Issue by paya-cz** [muak/AiForms.SettingsView#88]
### Description

Section's Footer does not resize to fit the content when FooterText spans multiple lines.

### Steps to Reproduce

1. Create a new Section and set FooterText to a very long text that spans multiple lines.

### Expected Behavior

The footer should auto-resize to show the entire FooterText.

### Actual Behavior

The content is clipped. Only the first line is showed.

### Platforms

- [ ] Android
- [x] iOS

### Basic Information

- AiForms.SettingsView 1.1.4-pre
- Xamarin.Forms 4.5.0

### Screenshots

<img width="345" alt="Screenshot 2020-03-20 at 20 26 09" src="https://user-images.githubusercontent.com/10402560/77167746-84051200-6aae-11ea-9b3a-867856e24279.png">

### Code

```xaml
<sv:Section Title="MultiPicker - lets see if the header will wrap to multiple lines when there is too much text. Lets see if the header will wrap to multiple lines when there is too much text."
            FooterText="This is a multi select picker. you are free to select items until MaxSelectedNumber. Let's see how much text can I put into the footer and if it wraps.">
    <sv:PickerCell Title="Favorites" ItemsSource="{Binding ItemsSource}" DisplayMember="Name" MaxSelectedNumber="3" 
    SelectedItems="{Binding SelectedItems}" KeepSelectedUntilBack="true" PageTitle="select 3 items" />
</sv:Section>
```

**Comment by muak** [comment]
@paya-cz 
Thank you for your report.

This issue was fixed at version 1.1.9-pre.
