### ISSUE TITLE
SettingsView's HeaderPadding is broken for vertical values

### ISSUE THREAD

**Issue by paya-cz** [muak/AiForms.SettingsView#89]
### Description

When the `SettingsView`'s `HeaderPadding.Top` or `HeaderPadding.Bottom` is set, the value does not have any effect on the view. The padding is not honored.

When the `HeaderPadding.Bottom` is set and `HeaderHeight` is also set, the behavior is strange, the header just floats over other elements.

### Steps to Reproduce

1. Set a custom `HeaderPadding` on `SettingsView`, particularly a custom `Top` and `Bottom` values.

### Expected Behavior

The content above the `Section`'s `Title` should be offset by the `HeaderPadding.Top`.
The content below the `Sections`'s `Title` should be offset by the `HeaderPadding.Bottom`.

### Actual Behavior

The `HeaderPadding.Top` and `HeaderPadding.Bottom` has no effect.

If the `HeaderHeight` is set, then `HeaderPadding.Bottom` causes the header to float over other elements.

### Platforms

- [ ] Android
- [x] iOS

### Basic Information

- AiForms.SettingsView 1.1.4-pre
- Xamarin.Forms 4.5.0

### Screenshot

<img width="345" alt="Screenshot 2020-03-20 at 20 42 31" src="https://user-images.githubusercontent.com/10402560/77169031-c0d20880-6ab0-11ea-9384-88594d685986.png">

### Code

```xaml
<sv:SettingsView HasUnevenRows="true"
                 HeaderPadding="14,100,0,6"
                 HeaderTextVerticalAlign="End"
                 FooterPadding="14,4,4,6"
                 ShowArrowIndicatorForAndroid="True">
```

This code is for HeaderPadding.Top. Modify HeaderPadding.Bottom to see it is also broken.

**Comment by muak** [comment]
@paya-cz 
Thank you for your report.

This issue was fixed at version 1.1.9-pre.
