### ISSUE TITLE
HintText does not respect SafeAreaInsets

### ISSUE THREAD

**Issue by paya-cz** [muak/AiForms.SettingsView#90]
### Description

`HintText` on a cell does not take `SafeAreaInsets` into account when positioning the label.

### Steps to Reproduce

1. Create a new cell and put a HintText on it.
2. Rotate the device to landscape.

### Expected Behavior

`HintText` should be aligned to respect `SafeAreaInsets`.

### Actual Behavior

`HintText` is oblivious to `SafeAreaInsets`.

### Platforms

- [ ] Android
- [x] iOS

### Basic Information

- AiForms.SettingsView 1.1.4-pre
- Xamarin.Forms 4.5.0

### Screenshots

<img width="736" alt="Screenshot 2020-03-21 at 03 36 12" src="https://user-images.githubusercontent.com/10402560/77204370-81c0a900-6aea-11ea-8b4c-5cb9d0d835a5.png">
<img width="736" alt="Screenshot 2020-03-21 at 03 36 28" src="https://user-images.githubusercontent.com/10402560/77204378-84bb9980-6aea-11ea-8ae7-b23407575dd6.png">

**Comment by muak** [comment]
@paya-cz 
Thank you for your report.

This issue was fixed at version 1.1.9-pre.
