### ISSUE TITLE
How to use it in code

### ISSUE THREAD

**Issue by B4DschK4Pp** [muak/AiForms.SettingsView#91]
### Description
I want to use SettingsView in code (not XAML) and created a SettingsView with two EntryCells. But when I launch the app on my iOS Simulator the page is just empty.
I added the the `AiForms.Effects.iOS.Effects.Init();` line in my AppDelegate.cs, and tried with a xaml approach and that worked as expected. 
But then I tried the code approach and the page shows just nothing.

```
using Xamarin.Forms;
using Xamarin.Forms.Xaml;
using sv = AiForms.Renderers;

namespace IDERInoteClient.MasterDetail
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class Page1 : ContentPage
    {
        public Page1()
        {
            InitializeComponent();       
            Content = new sv.SettingsView
            {
                HasUnevenRows = true,
                IsVisible = true,
                Root = new sv.SettingsRoot{
                    new sv.Section("MyTest"){
                        new sv.EntryCell { Title = "New Voice Mail" },
                        new sv.EntryCell { Title = "New Mail"}
                    }
                },
                Intent = TableIntent.Settings
            };
        }
    }
}
```

Did I miss something? In another test I also added 
`[assembly: XmlnsDefinition("SettingsView", "AiForms.Renderers")]` 
but had no luck with that either.

Are there any examples with code approach?

### Expected Behavior
My specified SettingsView showing

### Actual Behavior
Page empty

### Platforms

- [ ] Android
- [x] iOS

### Basic Information

- AiForms.SettingsView 1.0.9 (installed via NuGet Manager)
- Xamarin 16.5.000.521
- VS 2019 (16.5)

**Comment by muak** [comment]
@B4DschK4Pp 
Thank you for your report.

What write in the Applelegate.cs is not ``AiForms.Effects.iOS.Effects.Init()``  but ``AiForms.Renderers.iOS.SettingsViewInit.Init()``.

Please try it.

**Comment by Jakar510** [comment]
I would advise: 

`
              sv.SettingsView View { get; set; }
              sv.SettingsRoot Root { get; set; }

             Content = View = new sv.SettingsView
            {
                HasUnevenRows = true,
                IsVisible = true,
                
                Intent = TableIntent.Settings
            };
              Root = View.Root;
              Root.Add(sv.Section("MyTest") {
                        new sv.EntryCell { Title = "New Voice Mail" },
                        new sv.EntryCell { Title = "New Mail"}
                    });
`
