### ISSUE TITLE
why the TextPickerCell always default to the last item on android?

### ISSUE THREAD

**Issue by winsonet** [muak/AiForms.SettingsView#93]
for example as below datasource:
```
List<string> loanType = new List<string>(new List<string> {
               "test001", "test002","test003","test004"
            });
```
I expect the default selected item should be ```test001```,  but everytime popup on android it always default to ```test004```

![image](https://user-images.githubusercontent.com/1869995/78315285-22a17080-758f-11ea-868a-006c6de92343.png)

**Comment by muak** [comment]
@winsonet 
Thank you for your report.

I couldn't reproduce this issue. It worked fine.
Could you tell me more detailed information?

**Comment by winsonet** [comment]
hum....I don't know why, I just used the above code, and for now my solution is do the reverse with the array before show up:
```
 if (Device.RuntimePlatform == Device.Android)
{
     loanType.Reverse();
}

LoanType.Items = loanType;  //set the data source
```
this can make sure the sorting is what I want

and below is the xaml codes:
```
<sv:SettingsView
                Grid.Row="0"
                CellDescriptionColor="Red"
                CellHintFontSize="25"
                CellValueTextFontSize="15"
                FooterPadding="14,4,4,6"
                HasUnevenRows="true"
                HeaderFontSize="20"
                HeaderHeight="50"
                HeaderPadding="14,10,5,6"
                HeaderTextVerticalAlign="End"
                ShowArrowIndicatorForAndroid="True">

    <sv:Section Title="Account Info">
                    <sv:TextPickerCell
                        x:Name="LoanType"
                        Title="Loan Type"
                        PageTitle="Select the loan type" />
    </sv:Section>

</sv:SettingsView>
```

**Comment by muak** [comment]
@winsonet 
Thanks.

Could you tell me your basic information(Android ver. / SettingsView ver. / XF ver.)?

**Comment by winsonet** [comment]
ok, please find below information:

Anddroid ver:  10(or 9) and the api is  above API 29(or 28), actually I tried in the emulator and real device also same

SettinsView ver: 1.1.1-pre , also tried the latest version 1.1.9-pre

XF ver: 4.6.0.379-pre1

thanks!

**Comment by muak** [comment]
@winsonet 
Although I tried on API29 Simulator(Pixel3a) and API28 real device, I couldn't reproduce it.

In my environment, the picker is no loop.
![Screenshot_1590669697](https://user-images.githubusercontent.com/16084475/83142877-0f90c400-a12c-11ea-927e-148fc64bbd65.png)

**Comment by winsonet** [comment]
oh, that's so strange, ok, I created a sample for this, in this sample, I just use the ```AiForms.SettingsView``` and I also can reproduce this issue, can you please try it?

[SettingViewTest.zip](https://github.com/muak/AiForms.SettingsView/files/4696020/SettingViewTest.zip)

Thanks!

**Comment by muak** [comment]
@winsonet 
Thank you so much for your sample.

I could reproduce it!
When the Picker has more than four items, Picker items were circulated.
And if SelectedItem is null, the last item was selected.

I fixed it just now.
Please wait for the next release.

Thanks.

**Comment by winsonet** [comment]
oh, that's great! thanks!
