### ISSUE TITLE
[Enhancement] EntryCell Placeholder Color

### ISSUE THREAD

**Issue by Jakar510** [muak/AiForms.SettingsView#94]
## Summary
Please add a binding for an EntryCell Placeholder Color.

## API Changes

Please add a binding for an EntryCell Placeholder Color, as there is currently no way to set it:

	`<sv:EntryCell Title="EntryCell" 
	ValueText="{Binding InputText.Value}" 
	Placeholder="Input text" 
	Keyboard="Email" 
	TextAlignment="End" 
	ValueTextColor="{StaticResource TextColor}"
	HintTextColor="PaleVioletRed"
	DescriptionColor="{StaticResource CellDescriptionColor}"
	**PlaceholderColor**="{StaticResource CellPlaceHolderColor}"
	HintText="{Binding InputError.Value}" />`

## Intended Use Case
At a global level, you can set SettingsView.CellValueTextColor to a particular color. While this changes all values as expected, the default value, the placeholder, is affected. This causes a visual inconsistency.

**Comment by muak** [comment]
@Jakar510 
Thank you for your request.

This feature was implemented.
Please wait for the next release.
