### ISSUE TITLE
Cells do not support FontImageSource for icon

### ISSUE THREAD

**Issue by paya-cz** [muak/AiForms.SettingsView#95]
### Description

I use `ionicons.ttf` font to add font icons to Shell TabTab via `FontImageSource`. It works great. When I try to use the same `FontImageSource` for a cell icon, it only shows a blank space.

### Steps to Reproduce

1. Add an icon font to the project.
2. Create a new instance of `FontImageSource`
3. Use the `FontImageSource` as `IconSource` of a cell.

### Expected Behavior

The icon should render.

### Actual Behavior

The icon does not render.

### Platforms

- [x] Android
- [x] iOS

### Basic Information

- AiForms.SettingsView 1.1.4-pre
- Xamarin.Forms 4.5.0.617
- Affected Devices: iOS, Android

### Screenshots

<img width="341" alt="Screenshot 2020-04-16 at 17 46 31" src="https://user-images.githubusercontent.com/10402560/79448367-d3b4fb80-7fd0-11ea-9f1a-388f175634e7.png">

### Reproduction Link

[FontImageSourceBug.zip](https://github.com/muak/AiForms.SettingsView/files/4486583/FontImageSourceBug.zip)

### Workaround

Use SVG instead. No workaround for font icons.

**Comment by muak** [comment]
@paya-cz 
Thank you for your report.

This issue was fixed just now.
Please wait for the next release.
