### ISSUE TITLE
DateTimePicker crashes when the cell is tapped when the MinimumDate is set to DateTime.MinValue and MaximumDate is set to DateTime.MaxValue.

### ISSUE THREAD

**Issue by Jakar510** [muak/AiForms.SettingsView#98]
### Description

DateTimePicker crashes when the cell is tapped when the MinimumDate is set to DateTime.MinValue and MaximumDate is set to DateTime.MaxValue.

It occurs on Android and haven't tested iOS.

### Steps to Reproduce

1. Create DatePickerCell
- Set Format to "MM/dd/yyyy"
- Set MinimumDate to DateTime.MinValue
- Set MaximumDate to DateTime.MaxValue
- Set Title to any string
- Set ValueText to null
- Set Description to any string

2. Add DatePickerCell to Section and add it to the SettingsView.Root
3. Tap on the cell, the screenshot below shows the exception. 

### Expected Behavior

On tap of the cell, a popup window appears to select the date.

### Actual Behavior

On tap of the cell, I get the following exception: 

> System.ArgumentOutOfRangeException
>  Message=The added or subtracted value results in an un-representable DateTime.
> Parameter name: value

### Platforms

- [x] Android
- [ ] iOS 

### Basic Information

- AiForms.SettingsView x.x.x
- Xamarin.Forms x.x.x
- Android Support Library Version: 
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/49802225/79820622-47009980-8352-11ea-9199-5940ade77386.png)

### Reproduction Link

N/A

### Workaround

Don't set the respective values to Min and Max.

**Comment by muak** [comment]
@Jakar510 
Thank you for your report.

I fixed it just now.
Please wait for the next release.
